# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04e1430f60a5b7fa603fc70dc215a63198f120b001a1913ef6a26d0a1d9e6381f75d94fba6e1f150924c1a4c8c3a0e538cc6ced53a2f3d63900df26d9fcad88f

test:
  secret_key_base: acc540f7637f1fd42fda4fe2e9a7f8eb72f3c4db1c0f78aaf7f0551f74eccffb6657aa28f7d7f8cf8a8f3c5f9acf1934bd32cbb97872c6318f231dcdf52a7467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
